# Generated by Django 4.1.2 on 2022-11-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.CharField(max_length=1000)),
                ('java', models.CharField(max_length=1000)),
                ('php', models.CharField(max_length=1000)),
                ('React_js', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Python',
        ),
    ]
