# Generated by Django 4.1.2 on 2022-11-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0002_technologies_delete_python'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('technologies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobweb.technologies')),
                ('internship', models.CharField(max_length=1000)),
                ('Placement', models.CharField(max_length=1000)),
                ('Fresher', models.CharField(max_length=1000)),
            ],
            bases=('jobweb.technologies',),
        ),
    ]
